import type { Metadata } from "next";
import "./global.css";
import "./embla.css";
import { Header, Footer, Divider } from "@/components";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
  icons: {
    icon: "/fav/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="flex flex-col min-h-[100vh]">
          <Header />
          <div className="content-wrapper">{children}</div>
          <Footer className="mt-auto" />
        </main>
      </body>
    </html>
  );
}
