import type { Metadata } from "next";
import "./global.css";
import { Header, Footer } from "@/components";

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="flex flex-col min-h-[100vh]">
          <Header />
          <div className="bg-gray-500 h-[1px]" />
          {children}
          <div className="bg-gray-500 h-[1px] mt-auto" />
          <Footer />
        </main>
      </body>
    </html>
  );
}
